services:
  backend:
    build: ./backend
    container_name: jkd-backend
    env_file: .env
    restart: always

  frontend:
    build: ./frontend
    container_name: jkd-frontend
    ports:
      - "1240:80"
    depends_on:
      - backend
    restart: always

networks:
  default:
    name: xk_network
    external: true
